
steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/testing', '.', '--build-arg', '${_GDRIVE_CREDENTIALS_DATA}' ]

  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testing']