
steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/testing', '.', '--build-arg', '_GDRIVE_CREDENTIALS_DATA=${_GDRIVE_CREDENTIALS_DATA}', '--build-arg', '_WANDB_API_KEY=${_WANDB_API_KEY}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testing']

options:
    machineType: 'N1_HIGHCPU_8'
