
steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'build -t gcr.io/$PROJECT_ID/testing .'
  args:
    - 'GDRIVE_CREDENTIALS_DATA=${_GDRIVE_CREDENTIALS_DATA}'
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testing']