wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1673520001.198245
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.13.7
      8:
      - 4
      - 5
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: maximize
    name: val_acc
name:
  desc: null
  value: sweep
parameters:
  desc: null
  value:
    batch_size:
      values:
      - 32
      - 64
    epochs:
      values:
      - 5
      - 10
      - 15
    lr:
      max: 0.001
      min: 0.0001
program:
  desc: null
  value: train_model.py
