# config.yaml
program: train_model.py
method: random
name: sweep
metric:
  goal: maximize
  name: val_acc
parameters:
  batch_size: 
    values: [32,64]
  lr:
    min: 0.0001
    max: 0.001
  epochs:
    values: [5, 10, 15]